Run replicate push
  replicate push
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.6/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.6/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.6/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.6/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.6/x64/lib
    REPLICATE_API_TOKEN: ***
/home/runner/work/_temp/bf6006f9-2510-4e9a-a1f6-ccaf240b6dc9.sh: line 1: replicate: command not found
Error: Process completed with exit code 127.
