name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name: interior-ai
        description: 'erayyavuz/interior-ai'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Repository'i Klonla
        uses: actions/checkout@v4

      - name: Bağımlılıkları Yükle
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3-pip

      - name: Cog Kurulumu (pip ile)
        run: |
          pip3 install --user cog
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cog'un Yüklü Olduğunu Doğrula
        run: |
          echo "PATH: $PATH"
          echo "Listing ~/.local/bin:"
          ls -la $HOME/.local/bin
          echo "Which cog:"
          which cog
          echo "Cog versiyonu:"
          cog --version

      - name: Replicate’a Push Et
        run: cog push r8.im/${{ inputs.model_name }}
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
