name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Doğru şekilde yerleştirilmiş

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sürüm string olarak verilmelidir

      - name: Install Replicate CLI
        run: pip install replicate

      - name: Push the model to Replicate
        run: replicate push
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}  # API token'ı gizli olarak kullanıyoruz
