name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Kodları indirir

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Python sürümünü ayarlar

      - name: Install Replicate CLI
        run: |
          python -m pip install --user replicate  # Replicate CLI'yi kurar
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Local bin dizinini PATH'e ekler
          export PATH="$HOME/.local/bin:$PATH"  # PATH'i günceller
          replicate --version  # Replicate CLI'nin kurulu olduğunu kontrol eder

      - name: Push the model to Replicate
        run: replicate push  # Modeli Replicate'e gönderir
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}  # API token'ı kullanır
