name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Replicate CLI
        run: |
          python -m pip install --user replicate
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          ~/.local/bin/replicate --version  # CLI'nin tam yolunu kullanarak versiyonu kontrol et

      - name: Push the model to Replicate
        run: ~/.local/bin/replicate push  # Tam yol ile komutu çalıştır
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
