name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'erayyavuz/interior-ai'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      # 1. Repository'i Klonla
      - name: Repository'i Klonla
        uses: actions/checkout@v4

      # 2. Bağımlılıkları Yükle
      - name: Bağımlılıkları Yükle
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3-pip git

      # 3. pipx Kurulumu
      - name: pipx Kurulumu
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 4. Cog Repository'sini Klonla ve Kur
      - name: Cog Repository'sini Klonla ve Kur
        run: |
          git clone https://github.com/replicate/cog.git
          cd cog
          pipx install .

      # 5. Cog'u Doğrula
      - name: Cog'u Doğrula
        run: |
          cog --version

      # 6. Replicate’a Push Et
      - name: Replicate’a Push Et
        run: cog push r8.im/${{ inputs.model_name }}
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
