name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'erayyavuz/interior-ai'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Repository'i Klonla
        uses: actions/checkout@v4

      - name: Bağımlılıkları Yükle
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3-pip

      - name: pipx Kurulumu
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: pipx PATH'ini Güncelle
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cog Kurulumu (pipx ile)
        run: pipx install cog

      - name: Cog'un Yüklü Olduğunu Doğrula
        run: |
          echo "PATH: $PATH"
          which cog
          cog --version

      - name: Replicate’a Push Et
        run: cog push r8.im/${{ inputs.model_name }}
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
