name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install replicate

      - name: Push to replicate
        run: cog push r8.im/${{ inputs.model_name }}
        
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
