name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Replicate CLI
        run: |
          python -m pip install --user replicate
          export PATH="$HOME/.local/bin:$PATH"
          echo $PATH  # PATH’i kontrol et
          find $HOME/.local/bin -name "replicate"  # Replicate komutunu bul
          $HOME/.local/bin/replicate --version  # CLI’yi tam yolla çalıştır

      - name: Push the model to Replicate
        run: $HOME/.local/bin/replicate push .
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
