name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'erayyavuz/interior-ai'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      # 1. Repository'i Klonla
      - name: Repository'i Klonla
        uses: actions/checkout@v4

      # 2. Bağımlılıkları Yükle
      - name: Bağımlılıkları Yükle
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      # 3. Cog'u İndir ve Kur
      - name: Cog'u İndir ve Kur
        run: |
          # En son sürümü almak için GitHub API kullanın
          COG_VERSION=$(curl -s https://api.github.com/repos/replicate/cog/releases/latest | grep tag_name | cut -d '"' -f 4)
          echo "Cog sürümü: $COG_VERSION"
          
          # İndirme URL'sini oluştur
          COG_URL="https://github.com/replicate/cog/releases/download/${COG_VERSION}/cog-linux-amd64"
          
          # Cog'u indir
          curl -L -o cog ${COG_URL}
          
          # Cog'u çalıştırılabilir yap
          chmod +x cog
          
          # Cog'u ~/.local/bin dizinine taşı
          mkdir -p $HOME/.local/bin
          mv cog $HOME/.local/bin/
          
          # ~/.local/bin dizinini PATH'e ekle
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 4. Cog'u Doğrula
      - name: Cog'u Doğrula
        run: |
          which cog
          cog --version

      # 5. Replicate’a Push Et
      - name: Replicate’a Push Et
        run: cog push r8.im/${{ inputs.model_name }}
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
