name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Replicate CLI
        run: |
          pip install replicate
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH
          export PATH="$(python3 -m site --user-base)/bin:$PATH"
          replicate --version  # CLI'nin doğru yüklendiğini kontrol et

      - name: Push the model to Replicate
        run: replicate push .
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
