name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'erayyavuz/interior-ai'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      # 1. Repository'i Klonla
      - name: Repository'i Klonla
        uses: actions/checkout@v4

      # 2. Bağımlılıkları Yükle
      - name: Bağımlılıkları Yükle
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3-pip

      # 3. Cog Kurulumu
      - name: Cog Kurulumu
        run: |
          # 'install.sh' betiğini doğru şekilde çalıştırın
          curl -sSfL https://raw.githubusercontent.com/replicate/cog/main/install.sh | bash
          
          # ~/.local/bin dizinini PATH'e ekleyin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 4. Cog Kurulumunu Doğrula
      - name: Cog Kurulumunu Doğrula
        run: |
          # PATH değişkenini kontrol edin
          echo "PATH: $PATH"
          
          # ~/.local/bin dizinindeki dosyaları listeleyin
          ls -la $HOME/.local/bin
          
          # 'cog' komutunun yerini bulun
          which cog
          
          # 'cog' versiyonunu kontrol edin
          cog --version

      # 5. Replicate’a Push Et
      - name: Replicate’a Push Et
        run: cog push r8.im/${{ inputs.model_name }}
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
