name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'erayyavuz/interior-ai'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      # 1. Repository'i Klonla
      - name: Repository'i Klonla
        uses: actions/checkout@v4

      # 2. Cog'u Yükle
      - name: Cog'u Yükle
        run: |
          sudo curl -L https://github.com/replicate/cog/releases/download/v0.9.23/cog_Linux_x86_64 -o /usr/local/bin/cog
          sudo chmod +x /usr/local/bin/cog
          cog --version

      # 3. Hugging Face ve Replicate Token'larını Test Et
      - name: Hugging Face ve Replicate Token'larını Kontrol Et
        run: |
          if [ -z "$HUGGINGFACE_TOKEN" ]; then
            echo "Hugging Face API token bulunamadı!"
            exit 1
          else
            echo "Hugging Face API token bulundu: $HUGGINGFACE_TOKEN"
          fi

          if [ -z "$REPLICATE_API_TOKEN" ]; then
            echo "Replicate API token bulunamadı!"
            exit 1
          else
            echo "Replicate API token bulundu: $REPLICATE_API_TOKEN"
          fi
        env:
          HUGGINGFACE_TOKEN: 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  # Hugging Face token burada tanımlandı
          REPLICATE_API_TOKEN: ${{
