name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Replicate CLI
        run: |
          sudo pip install replicate  # Global olarak yükle
          replicate --version  # CLI'nin doğru yüklendiğini kontrol et

      - name: Push the model to Replicate
        run: replicate push .
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
