name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install replicate

      - name: Push the model via Python
        run: |
          python -c "
          import replicate;
          client = replicate.Client();
          model = client.models.get('erayyavuz/interior-ai');
          model.versions.create(files=['./predict.py', './cog.yaml'])
          "
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
