name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Replicate CLI
        run: |
          python -m pip install --user replicate
          export PATH="$HOME/.local/bin:$PATH"  # PATH'i güncelle
          python3 -m site  # Python'ın kullanıcı tabanlı dizinini kontrol et
          ~/.local/bin/replicate --version  # CLI'nin yüklendiğini doğrula

      - name: Push the model to Replicate
        run: ~/.local/bin/replicate push .
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
