name: Push to Replicate
 
on:
  workflow_dispatch:
    inputs:
      model_name: interior-ai
        description: 'erayyavuz/interior-ai'
        required: true
 
jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cog
        run: |
          curl -o cog https://raw.githubusercontent.com/replicate/cog/main/install.sh | bash
          chmod +x cog
          ./cog --version

      - name: Push to Replicate
        run: ./cog push r8.im/${{ inputs.model_name }}
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
