name: Push Model to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Replicate CLI Globally
        run: |
          sudo pip install replicate
          sudo ln -s $(which replicate) /usr/local/bin/replicate  # Yolu global olarak ekle
          replicate --version  # CLI'nin çalışıp çalışmadığını kontrol et

      - name: Push the model to Replicate
        run: replicate push .
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
